version: 2

project_name: terraform-provider-hiiretail

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}_v{{ .Version }}"
    main: ./
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - cmd: gpg
    args: ["--batch", "--local-user", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    artifacts: checksum

release:
  github:
    owner: extenda
    name: terraform-provider-hiiretail
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto
  footer: |
    ## Installation
    
    See the [documentation](https://registry.terraform.io/providers/extenda/hiiretail/{{ .Version }}/docs) for installation instructions.
    
    ## Changes
    
    See [CHANGELOG.md](https://github.com/extenda/terraform-provider-hiiretail/blob/main/CHANGELOG.md) for detailed changes.