// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_hiiretail_iam

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func HiiretailIamProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type HiiretailIamModel struct {
}
