// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_iam_group

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/extenda/hiiretail-terraform-providers/internal/validation"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IamGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(255),
					validation.NewDescriptionValidator("group"),
				},
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "An optional id of a group. Will be auto-generated if not passed",
				MarkdownDescription: "An optional id of a group. Will be auto-generated if not passed",
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(255),
					validation.NewNameValidator("group"),
				},
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"tenant_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type IamGroupModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Status      types.String `tfsdk:"status"`
	TenantId    types.String `tfsdk:"tenant_id"`
}
