// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_iam_role

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IamRoleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"fixed_bindings": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Role id must follow the pattern: {systemPrefix}.{role} and contain a-z letters and hyphens where the systemPrefix size is 3 and role is between 2 and 30 characters.",
				MarkdownDescription: "Role id must follow the pattern: {systemPrefix}.{role} and contain a-z letters and hyphens where the systemPrefix size is 3 and role is between 2 and 30 characters.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z][-a-z]{2}\\.[a-z][-a-z]{1,29}$"), ""),
				},
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 256),
				},
			},
			"permissions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"return_aliases": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set to true, permissions array will contain permission aliases instead of permission ids (or id if no alias is found)",
				MarkdownDescription: "If set to true, permissions array will contain permission aliases instead of permission ids (or id if no alias is found)",
			},
		},
	}
}

type IamRoleModel struct {
	FixedBindings types.List   `tfsdk:"fixed_bindings"`
	Id            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	Permissions   types.List   `tfsdk:"permissions"`
	ReturnAliases types.Bool   `tfsdk:"return_aliases"`
}
