// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_iam_role_binding

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IamRoleBindingResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bindings": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
				Validators: []validator.List{
					listvalidator.SizeAtMost(10),
				},
			},
			"id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"is_custom": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"role_id": schema.StringAttribute{
				Required: true,
			},
			"tenant_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type IamRoleBindingModel struct {
	Bindings types.List   `tfsdk:"bindings"`
	Id       types.String `tfsdk:"id"`
	IsCustom types.Bool   `tfsdk:"is_custom"`
	RoleId   types.String `tfsdk:"role_id"`
	TenantId types.String `tfsdk:"tenant_id"`
}
