openapi: 3.0.3
info:
  title: HiiRetail IAM Role Binding API
  description: API contract for IAM Role Binding resource operations
  version: 1.0.0
servers:
  - url: https://api.hiiretail.com/iam/v1
    description: Production API
  - url: http://localhost:8080/iam/v1  
    description: Mock server for testing

security:
  - oauth2_client_credentials: []

paths:
  /role-bindings:
    post:
      summary: Create a new role binding
      operationId: createRoleBinding
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleBindingRequest'
            examples:
              user_binding:
                summary: Bind role to user
                value:
                  role_id: "custom-role-123"
                  is_custom: true
                  bindings:
                    - type: "user"
                      subject_id: "user-456"
              group_binding:
                summary: Bind role to group
                value:
                  role_id: "system-role-789"
                  is_custom: false
                  bindings:
                    - type: "group"
                      subject_id: "group-101"
              multiple_bindings:
                summary: Multiple bindings
                value:
                  role_id: "custom-role-123"
                  is_custom: true
                  bindings:
                    - type: "user"
                      subject_id: "user-456"
                    - type: "group"
                      subject_id: "group-789"
      responses:
        '201':
          description: Role binding created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleBindingResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                max_bindings:
                  summary: Too many bindings
                  value:
                    error: "validation_error"
                    message: "Maximum 10 bindings allowed per resource"
                    code: "MAX_BINDINGS_EXCEEDED"
                invalid_role:
                  summary: Invalid role reference
                  value:
                    error: "validation_error"
                    message: "Role not found or access denied"
                    code: "INVALID_ROLE_ID"
        '401':
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /role-bindings/{id}:
    get:
      summary: Get role binding by ID
      operationId: getRoleBinding
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Role binding retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleBindingResponse'
        '404':
          description: Role binding not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication required
        '403':
          description: Insufficient permissions

    put:
      summary: Update role binding
      operationId: updateRoleBinding
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleBindingRequest'
      responses:
        '200':
          description: Role binding updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleBindingResponse'
        '400':
          description: Validation error
        '404':
          description: Role binding not found
        '401':
          description: Authentication required
        '403':
          description: Insufficient permissions

    delete:
      summary: Delete role binding
      operationId: deleteRoleBinding
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Role binding deleted successfully
        '404':
          description: Role binding not found
        '401':
          description: Authentication required
        '403':
          description: Insufficient permissions

components:
  securitySchemes:
    oauth2_client_credentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.hiiretail.com/oauth2/token
          scopes:
            iam:role-bindings:read: Read role bindings
            iam:role-bindings:write: Create and update role bindings
            iam:role-bindings:delete: Delete role bindings

  schemas:
    RoleBindingRequest:
      type: object
      required:
        - role_id
        - bindings
      properties:
        role_id:
          type: string
          description: ID of the role to bind
          example: "custom-role-123"
        is_custom:
          type: boolean
          description: Whether this binding applies to custom roles
          default: false
        bindings:
          type: array
          description: List of user/group bindings
          minItems: 1
          maxItems: 10
          items:
            $ref: '#/components/schemas/Binding'

    RoleBindingResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the role binding
          example: "rb-550e8400-e29b-41d4-a716-446655440000"
        role_id:
          type: string
          description: ID of the bound role
          example: "custom-role-123"
        is_custom:
          type: boolean
          description: Whether this binding applies to custom roles
        bindings:
          type: array
          items:
            $ref: '#/components/schemas/Binding'
        tenant_id:
          type: string
          description: Tenant context for isolation
          example: "tenant-abc-123"
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    Binding:
      type: object
      required:
        - type
        - subject_id
      properties:
        type:
          type: string
          enum: ["user", "group"]
          description: Type of binding subject
        subject_id:
          type: string
          description: ID of the user or group
          example: "user-456"
        principal:
          type: string
          description: Optional principal identifier
          example: "john.doe@company.com"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error type
          example: "validation_error"
        message:
          type: string
          description: Human-readable error message
          example: "Maximum 10 bindings allowed per resource"
        code:
          type: string
          description: Machine-readable error code
          example: "MAX_BINDINGS_EXCEEDED"
        details:
          type: object
          description: Additional error details
          additionalProperties: true